package com.jerseyhub.common.exception;

public enum ErrorCode {
    INTERNAL_SERVER_ERROR("ERR_INTERNAL_SERVER_ERROR"),
    INVALID_REQUEST("ERR_INVALID_REQUEST"),
    UNAUTHORIZED("ERR_UNAUTHORIZED"),
    FORBIDDEN("ERR_FORBIDDEN"),
    RESOURCE_NOT_FOUND("ERR_RESOURCE_NOT_FOUND"),
    METHOD_NOT_ALLOWED("ERR_METHOD_NOT_ALLOWED"),
    MALFORMED_REQUEST("ERR_MALFORMED_REQUEST"),
    TYPE_MISMATCH("ERR_TYPE_MISMATCH"),
    INVALID_CREDENTIALS("ERR_INVALID_CREDENTIALS"),
    ACCOUNT_DISABLED("ERR_ACCOUNT_DISABLED"),
    INVALID_REFRESH_TOKEN("ERR_INVALID_REFRESH_TOKEN"),
    REFRESH_TOKEN_EXPIRED("ERR_REFRESH_TOKEN_EXPIRED"),
    PRODUCT_NOT_FOUND("ERR_PRODUCT_NOT_FOUND"),
    CATEGORY_NOT_FOUND("ERR_CATEGORY_NOT_FOUND"),
    VARIANT_NOT_FOUND("ERR_VARIANT_NOT_FOUND"),
    IMAGE_NOT_FOUND("ERR_IMAGE_NOT_FOUND"),
    DUPLICATE_SKU("ERR_DUPLICATE_SKU"),
    DUPLICATE_SLUG("ERR_DUPLICATE_SLUG"),
    INSUFFICIENT_STOCK("ERR_INSUFFICIENT_STOCK"),
    INVALID_CATEGORY_HIERARCHY("ERR_INVALID_CATEGORY_HIERARCHY"),
    PRODUCT_INACTIVE("ERR_PRODUCT_INACTIVE"),
    VARIANT_INACTIVE("ERR_VARIANT_INACTIVE"),
    CART_EMPTY("ERR_CART_EMPTY"),
    ORDER_NOT_FOUND("ERR_ORDER_NOT_FOUND"),
    ORDER_NOT_CANCELLABLE("ERR_ORDER_NOT_CANCELLABLE"),
    ADDRESS_NOT_FOUND("ERR_ADDRESS_NOT_FOUND"),
    REVIEW_NOT_FOUND("ERR_REVIEW_NOT_FOUND"),
    REVIEW_ALREADY_EXISTS("ERR_REVIEW_ALREADY_EXISTS"),
    VERIFIED_PURCHASE_REQUIRED("ERR_VERIFIED_PURCHASE_REQUIRED"),
    COUPON_NOT_FOUND("ERR_COUPON_NOT_FOUND"),
    COUPON_INVALID("ERR_COUPON_INVALID"),
    COUPON_EXPIRED("ERR_COUPON_EXPIRED"),
    COUPON_NOT_STARTED("ERR_COUPON_NOT_STARTED"),
    COUPON_USAGE_LIMIT_REACHED("ERR_COUPON_USAGE_LIMIT_REACHED"),
    COUPON_USER_LIMIT_REACHED("ERR_COUPON_USER_LIMIT_REACHED"),
    COUPON_MIN_ORDER_NOT_MET("ERR_COUPON_MIN_ORDER_NOT_MET"),
    COUPON_ALREADY_APPLIED("ERR_COUPON_ALREADY_APPLIED"),
    COUPON_CODE_ALREADY_EXISTS("ERR_COUPON_CODE_ALREADY_EXISTS");

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return code;
    }
}
